### ISSUE TITLE
MVCCaching.Kentico.Examples Don't Compile

### ISSUE THREAD

**Issue by jknopp** [KenticoDevTrev/MVCCaching#4]
@KenticoDevTrev I was taking a look at the examples and trying to add them to your boilerplate MVC project, however, it appears that the 2 Service implementations are incomplete.

KenticoExampleModuleClassRepository inherits from IExampleModuleClassRepository but doesn't implement 2 of the required members:
GetExampleModuleClassesCacheDependency()
GetExampleModuleClassCacheDependency(int ID)

And KenticoExamplePageTypeRepository inherits from IExamplePageTypeRepository but doesn't implement 2 of the require members also:
GetExamplePagesCacheDependency()
GetExamplePageCacheDependency(int ID)

Are you able to point me anywhere that could help me understand how these 2 methods of each interface should be implemented?

Much appreciated and cool projects, I look forward to getting more familiar with them.

**Comment by jknopp** [comment]
I believe I found what I needed here: https://github.com/KenticoDevTrev/KenticoBoilerplate_v12/blob/BoilerplateVariants/CacheEnabled/Boilerplate/Repositories/Implementations/

Looks like those 2 methods may not have been ported from the old Boilerplate to the new standalone repo.

**Comment by KenticoDevTrev** [comment]
The boilerplate is a bit dated, still usable but you need to install all the various tools. Soon (hopefully) the next baseline project will be live to use, which is a better starting point but i haven't had time to finish it yet.

Remember though those samples on the caching repo are just that, samples, trust the documentation more!

**Comment by KenticoDevTrev** [comment]
The Boilerplate is now retired, and the [Baseline](https://github.com/HBSTech/Kentico12Baseline) project is now the current one, and contains examples of MVCCaching usage.
