### ISSUE TITLE
CachingRepositoryDecorator /Home Cache Keys

### ISSUE THREAD

**Issue by jknopp** [KenticoDevTrev/MVCCaching#5]
While trying to better understand the caching mechanisms here, I came across the following scenario which appears to be a bug. Curious to hear your thoughts.

Running the Baseline project and loading the homepage adds the following cache items:
Cache Key | Cache Dependencies | Cache Data
------------ | ------------- | -------------
node\|kickstarttemplate\|/home\|childnodes |  | (dummy item)
cachingrepositorydecorator\|data\|kickstarttemplate\|</br>kickstarttemplate.webapp.repositories.implementations.</br>kenticogeneraldocumentrepository\|getdocuments\|en-us\|/home\|parentandchildren\|generic.home\|\|\|-1\|1\|component_pagemetadata-documentname-documentid\|false | node\|kickstarttemplate\|/home\|childnodes | CMS.DataEngine.InfoDataSet`1[[CMS.DocumentEngine.TreeNode, CMS.DocumentEngine, Version=12.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9]]

However, I notice that when I save the /Home document in Kentico, the following cache keys are touched:
```javascript
[
   "node|kickstarttemplate|/home",
   "node|kickstarttemplate|/home|en-us",
   "nodeid|35",
   "documentid|35",
   "documentid|35|attachments",
   "nodes|kickstarttemplate|generic.home|all",
   "nodeguid|kickstarttemplate|b7bfc6a6-2f21-49ef-87bd-c3167918e04f",
   "node|kickstarttemplate|/|childnodes"
]
```

It appears as though the /home document may need to be translated to it's index url (/) instead of the full "/home" path, as I would anticipate these 2 keys being the same.

Cache repository dependency and dummy key:
"node|kickstarttemplate|/home|childnodes"

Kentico Admin:
"node|kickstarttemplate|/|childnodes"

**Comment by KenticoDevTrev** [comment]
The node|kickstarttemplate|/|childnodes will be triggered on all page updates as the home page is a child of the root node. The parameter is the node alias path.  I may be forgetting to add other normal node|kickstarttemplate|/home dependency But I believe this is covered the dependency on all generic.home page types

**Comment by jknopp** [comment]
Ahhh, thanks for the note, that makes sense and I think I was misinterpreting what was happening.

Saving the /Home page in the Kentico admin will touch:
"node|kickstarttemplate|/|childnodes"
Meaning anything dependent upon the children of the root should be cleared.

While loading the homepage, the CachingRepositoryDecorator adds the cache dependency:
"node|kickstarttemplate|/home|childnodes"
Meaning anything that touches the key for the /Home child nodes, should cause the KenticoGeneralDocumentRepository.GetDocuments cache to clear. 

My assumption is that is because of the PathSelectionEnum parameter which allows you to specify 'ParentAndChildren' or 'ChildrenOnly'?

**Comment by KenticoDevTrev** [comment]
You do have one point, the GetDocuments method should have 2 cache
dependencies, the one it has and node|##sitename##|{0}

**Comment by KenticoDevTrev** [comment]
I updated hte Baseline site to have both CacheDependencies that it should have.  Since this is a bug just in my implementation and not the actual tool, closing it down, you can look at the fix [here](https://github.com/HBSTech/Kentico12Baseline/blob/master/MVC/MVC/Repositories/Implementations/KenticoGeneralDocumentRepository.cs)
